org.gradle.jvmargs=-Xmx4G

available_loaders=fabric

mod_version=26.2-SNAPSHOT
maven_group=baritone
archives_base_name=baritone

java_version=25

minecraft_version=26.2

fabric_version=0.19.3

nether_pathfinder_version=1.4.1

// while mod loaders usually ship their own version
mixin_version=0.8.7
asm_version=9.7
